[workspace]
members = [
    "crates/rusty-knowledge",
    "crates/rusty-knowledge-todoist",
    "crates/query-render",
    "crates/rusty-knowledge-macros",
    "crates/rusty-knowledge-macros-test",
    "frontends/tui",
]
exclude = [
    "frontends/flutter/rust",
]
resolver = "2"
