[target.wasm32-unknown-unknown]
linker = "/opt/homebrew/opt/llvm/bin/clang"
ar = "/opt/homebrew/opt/llvm/bin/llvm-ar"
rustflags = ["-C", "link-arg=-fuse-ld=/opt/homebrew/opt/lld/bin/wasm-ld", "-C", "link-arg=--target=wasm32-unknown-unknown"]
